[libdefaults]
    default_realm = FATECSEG.LOCAL
[realms]
    FATECSEG.LOCAL  =  {
    kdc  =  pisrc-srv1.fatecseg.local
    default_domain  =  FATECSEG.LOCAL
    admin_server  =  pisrc-srv1.fatecseg.local
    kpasswd_server = pisrc-srv1.fatecseg.local
}
[domain_realm]
    .fatecseg.local = FATECSEG.LOCAL
    fatecseg.local = FATECSEG.LOCAL
