[global]
        bind interfaces only = Yes
        dedicated keytab file = /etc/krb5.keytab
        interfaces = enp0s3
        kerberos method = secrets and keytab
        realm = FATECSEG.LOCAL
        security = ADS
        server role = member server
        template homedir = /home/%U
        template shell = /bin/bash
        winbind enum groups = Yes
        winbind enum users = Yes
        winbind offline logon = Yes
        winbind refresh tickets = Yes
        winbind use default domain = Yes
        workgroup = FATECSEG
        idmap config fatecseg : range = 10000-999999
        idmap config fatecseg : backend = rid
        idmap config * : range = 3000-7999
        idmap config * : backend = tdb
        map acl inherit = Yes
        store dos attributes = Yes
        vfs objects = acl_xattr
