# =========================
# Configuração Global Samba
# =========================
[global]

        # Escuta apenas nas interfaces definidas abaixo
        bind interfaces only = Yes

        # Arquivo keytab Kerberos utilizado pelo sistema
        dedicated keytab file = /etc/krb5.keytab

        # Interface de rede utilizada pelo Samba
        interfaces = enp0s3

        # Usa secrets.tdb + keytab para autenticação Kerberos
        kerberos method = secrets and keytab

        # Realm Kerberos (domínio AD)
        realm = FATECSEG.LOCAL

        # Integração com Active Directory
        security = ADS

        # Define este host como membro do domínio (não DC)
        server role = member server

        # Diretório home padrão dos usuários AD
        template homedir = /home/%U

        # Shell padrão para usuários do AD
        template shell = /bin/bash

        # Permite listar grupos do domínio
        winbind enum groups = Yes

        # Permite listar usuários do domínio
        winbind enum users = Yes

        # Permite login em cache se o DC estiver offline
        winbind offline logon = Yes

        # Renova tickets Kerberos automaticamente
        winbind refresh tickets = Yes

        # Permite usar apenas o nome do usuário sem DOMINIO\
        winbind use default domain = Yes

        # Nome NetBIOS do domínio
        workgroup = FATECSEG

        # Backend padrão de mapeamento SID -> UID/GID
        idmap config * : backend = tdb

        # Faixa UID/GID padrão para domínios desconhecidos
        idmap config * : range = 3000-7999

        # Usa RID para gerar UID/GID automaticamente
        idmap config fatecseg : backend = rid

        # Faixa UID/GID usada para usuários do domínio
        idmap config fatecseg : range = 10000-999999

        # Herança de ACL estilo Windows
        map acl inherit = Yes

        # Armazena atributos DOS/Windows no filesystem Linux
        store dos attributes = Yes

        # Habilita ACL NTFS via extended attributes
        vfs objects = acl_xattr
