[global]
   workgroup = FATECSEG
   security = ADS
   realm = FATECSEG.LOCAL

   kerberos method = secrets and keytab
   dedicated keytab file = /etc/krb5.keytab

   winbind use default domain = yes
   winbind refresh tickets = yes
   winbind offline logon = yes
   winbind enum users = yes
   winbind enum groups = yes

   idmap config * : backend = tdb
   idmap config * : range = 3000-7999

   idmap config FATECSEG : backend = rid
   idmap config FATECSEG : range = 10000-999999

   template homedir = /home/%U
   template shell = /bin/bash

   vfs objects = acl_xattr
   map acl inherit = yes
   store dos attributes = yes
