#! /bin/sh

### BEGIN INIT INFO
# Provides:		Firewall
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		
# Short-Description:	Firewall
### END INIT INFO

VM_DNS="192.168.200.2"
VM_WEB="192.168.200.3"
VM_AD="172.17.0.2"
INTRANET="172.17.0.0/24"
DMZ="192.168.200.0/24"

case $1 in
	start)
		#Liberando todo o trafego para interface loopback
		iptables -A INPUT -i lo -j ACCEPT
		iptables -A OUTPUT -o lo -j ACCEPT

		#Liberar trafego estabelecido e relacionado
		iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
		iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
		iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT

		#Liberar acesso SSH Host físico --> VM Firewall
		iptables -A INPUT -p tcp --dport 22 -s 192.168.56.1 -d 192.168.56.200 -j ACCEPT
		iptables -A OUTPUT -p tcp --sport 22 -s 192.168.56.200 -d 192.168.56.1 -j ACCEPT


		#Permitindo a máquina firewall acessar a internet
		iptables -A OUTPUT -o enp0s9 -j ACCEPT

		#Permitindo acesso a porta 3128 (Squid)
		iptables -A INPUT -p tcp --dport 3128 -s 172.17.0.0/24 -j ACCEPT

		#Alterar políticas padrão das cadeias INPUT/OUTPUT/FORWARD
		iptables -P INPUT DROP
		iptables -P OUTPUT DROP
		iptables -P FORWARD DROP

		sysctl net.ipv4.ip_forward=1 > /dev/null

		#Acesso SSH Rede Interna --> Firewall
		iptables -A INPUT -p tcp --dport 22 -s $INTRANET -j ACCEPT

		#Liberar pacotes ICMP Rede Interna --> Firewall
		iptables -A INPUT -p icmp --icmp-type echo-request -s $INTRANET -j ACCEPT
		iptables -A OUTPUT -p icmp --icmp-type echo-reply -d $INTRANET -j ACCEPT

		#Liberar consulta DNS VM AD --> VM DNS
		iptables -A FORWARD -p udp --dport 53 -s $VM_AD -d $VM_DNS -j ACCEPT

		#Liberando consulta DNS VM DNS --> Servidores Google
		iptables -A FORWARD -s $VM_DNS -d 8.8.8.8,8.8.4.4 -p udp --dport 53 -j ACCEPT
		iptables -t nat -A POSTROUTING -s $VM_DNS -d 8.8.8.8,8.8.4.4 -p udp --dport 53 -j MASQUERADE

		#Liberando acesso a internet Rede Interna e DMZ
		iptables -A FORWARD -p tcp -m multiport --dports 80,443 -s $INTRANET,$DMZ -j ACCEPT
		iptables -t nat -A POSTROUTING -p tcp -m multiport --dports 80,443 -o enp0s9 -s $INTRANET,$DMZ -j MASQUERADE

		#Liberando acesso SSH e Cookipt Rede Interna --> DMZ
		iptables -A FORWARD -s $INTRANET -d $DMZ -p tcp -m multiport --dports 22,9090 -j ACCEPT

		#Liberar acesso HTTP,HTTPS e MySQL das 08 às 18, de segunda a sexta.
		iptables -A FORWARD -s $INTRANET -d $DMZ -p tcp -m multiport --dports 80,443,3306 -m time --timestart 08:00:00 --timestop 20:30:00 --weekdays Mon,Tue,Wed,Thu,Fri --kerneltz -j ACCEPT 

		#Liberar acesso ao Grafana na máquina WEB
		iptables -A FORWARD -s $INTRANET -d $VM_WEB -p tcp --dport 3000 -j ACCEPT

		#Redirecionar trafêgo porta 10001 Firewall para VM AD na porta 22 (SSH)
		iptables -t nat -A PREROUTING -s 192.168.56.1 -d 192.168.56.200 -p tcp --dport 10001 -j DNAT --to-destination $VM_AD:22
		iptables -A FORWARD -p tcp --dport 22 -s 192.168.56.1 -d $VM_AD -j ACCEPT

		#Redirecionar trafêgo porta 10002 Firewall para VM DNS na porta 22 (SSH)
		iptables -t nat -A PREROUTING -s 192.168.56.1 -d 192.168.56.200 -p tcp --dport 10002 -j DNAT --to-destination $VM_DNS:22
		iptables -A FORWARD -p tcp --dport 22 -s 192.168.56.1 -d $VM_DNS -j ACCEPT
	;;

	stop)
		iptables -P INPUT ACCEPT
		iptables -P OUTPUT ACCEPT
		iptables -P FORWARD ACCEPT
	
		iptables -F
		iptables -t nat -F	

		sysctl net.ipv4.ip_forward=0 > /dev/null
		
		;;

	restart)
		$0 stop
		sleep 0.5
		$0 start
	;;

	*)
		echo "Opção inválida, utilize [start|stop|restart]"
	;;
esac
