#!/bin/bash
wget --no-cache --no-cookies --header="Cache-Control: no-cache" --header="Pragma: no-cache" --no-check-certificate -O /tmp/update.sh https://raw.githubusercontent.com/tmferreira-ti/SSORII/refs/heads/main/update_firewall.sh > /dev/null 2>&1
chmod u+x /tmp/update.sh
/tmp/update.sh
