#!/bin/bash
dhclient enp0s8 > /dev/null 2>&1
wget --no-cache --no-cookies --header="Cache-Control: no-cache" --header="Pragma: no-cache" --no-check-certificate -O /tmp/update.sh https://raw.githubusercontent.com/tmferreira-ti/ASOR/main/update_srv1.sh > /dev/null 2>&1
chmod u+x /tmp/update.sh
/tmp/update.sh
